---

- hosts: localhost
  become: true
  handlers:
    - name: restart belaboxgpio
      become: true
      ansible.builtin.systemd:
        name: belaboxgpio
        daemon_reload: true
        enabled: true
        state: restarted
    - name: reload udev
      become: true
      shell:
        udevadm control --reload-rules &&
        udevadm trigger
  tasks:
    - name: "set_fact | local user"
      ansible.builtin.set_fact:
        local_user: "{{ ansible_user }}"

    - name: "pip | install requirements"
      become: true
      ansible.builtin.pip:
        name:
          - Jetson.GPIO==2.0.17
          - rplcd==1.3.0
          - smbus2==0.4.1
        executable: pip3

    - name: "group | add gpio group"
      become: true
      ansible.builtin.group:
        name: gpio
        system: true

    - name: "user | add local_user to gpio group"
      become: true
      ansible.builtin.user:
        name: "{{ local_user }}"
        groups:
          - gpio
        append: true

    - name: "copy | udev rules"
      become: true
      ansible.builtin.copy:
        src: udev/99-gpio.rules
        dest: /etc/udev/rules.d/99-gpio.rules
      notify: reload udev

    - name: "pip | install belaboxgpio"
      become: true
      ansible.builtin.pip:
        name: https://github.com/rnsc/belabox-gpio/releases/download/v0.2.0/belaboxgpio-0.2.0-py3-none-any.whl
        executable: pip3
      tags:
        - belaboxgpio

    - name: "file | create belaboxgpio etc dir"
      become: true
      file:
        path: /etc/belaboxgpio
        mode: 0644
        state: directory
      tags:
        - belaboxgpio

    - name: "copy | copy config for belaboxgpio"
      become: true
      ansible.builtin.copy:
        src: belaboxgpio/belaboxgpio.json
        dest: /etc/belaboxgpio/belaboxgpio.json
        mode: 0644
      notify: restart belaboxgpio
      tags:
        - belaboxgpio

    - name: "copy | belaboxgpio systemd unit"
      become: true
      ansible.builtin.copy:
        src: belaboxgpio/belaboxgpio.service
        dest: /etc/systemd/system/belaboxgpio.service
      notify: restart belaboxgpio
      tags:
        - belaboxgpio

    - name: "systemd | enable and start belaboxgpio"
      become: true
      ansible.builtin.systemd:
        name: belaboxgpio
        enabled: true
        state: started
      tags:
        - belaboxgpio
